#!/usr/bin/env python3
"""Regenerates the enum fixtures in testdata/ from the published protos.

Two enums, two files, one job: EmailEventType from event.proto becomes
event-types.json, and WebhookTriggerEvent from webhook.proto becomes
webhook-events.json. They are different vocabularies for different things —
the first names the state a message is in and comes back from a send, the
second names why a webhook fired — and conflating them is how a receiver ends
up matching on a string the gateway never sends.

The clients are hand-written on purpose — there is no protobuf runtime and no
generated code to keep in step, which is the whole reason the wire contract is
written down in docs/WIRE.md. So this does not generate the constants. It
generates the list the three test suites check them against, which keeps the
proto the source of truth without putting a code generator in the build.

Run it after scripts/sync-proto.sh, and commit whatever it produces.
"""

import collections
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENUMS = [
    {
        "proto": "event.proto",
        "enum": "EmailEventType",
        "prefix": "EMAIL_EVENT_TYPE_",
        "fixture": "event-types.json",
        "comment": [
            "Every value of EmailEventType in proto/panmail/v1/event.proto, and the",
            "only place the three clients' Status constants are written down together.",
            "Each suite reads this and asserts its own client exposes exactly these, so",
            "a value added to the proto that the clients do not follow fails all three.",
            "",
            "This is the state a message is in, and what a send returns. It is not the",
            "webhook vocabulary — see webhook-events.json for that.",
            "",
            "Generated by scripts/sync-status.py. Do not hand-edit: run that after the",
            "proto changes, the same way the protos themselves are synced.",
            "",
            "UNSPECIFIED is here because the proto has it. It is the zero value",
            "protobuf requires, not a state a message is ever in.",
        ],
    },
    {
        "proto": "webhook.proto",
        "enum": "WebhookTriggerEvent",
        "prefix": "WEBHOOK_TRIGGER_EVENT_",
        "fixture": "webhook-events.json",
        "comment": [
            "Every value of WebhookTriggerEvent in proto/panmail/v1/webhook.proto, and",
            "the only place the three clients' TriggerEvent constants are written down",
            "together.",
            "",
            "This is what a webhook delivery carries, in the X-Panmail-Event header and",
            "the envelope's \"event\" field. The gateway sends the proto enum name",
            "verbatim — WEBHOOK_TRIGGER_EVENT_MAIL_BOUNCED — because it dispatches with",
            "event.String(). It is emphatically not a dotted name like \"mail.bounced\":",
            "those appear in the gateway's own tests as arbitrary fixtures passed to a",
            "string parameter, and matching on them gives you a handler that never",
            "fires.",
            "",
            "Distinct from EmailEventType in event-types.json, which names the state a",
            "message is in. MAIL_REJECTED here is a provider refusing a send;",
            "MAIL_QUARANTINE_REJECTED is a person refusing a held one.",
            "",
            "Generated by scripts/sync-status.py. Do not hand-edit.",
        ],
    },
]


def main() -> int:
    for spec in ENUMS:
        proto = ROOT / "proto" / "panmail" / "v1" / spec["proto"]
        source = proto.read_text(encoding="utf-8")

        match = re.search(r"enum " + spec["enum"] + r" \{(.*?)\n\}", source, re.S)
        if match is None:
            print(f"no {spec['enum']} enum in {proto}", file=sys.stderr)
            return 1

        values = re.findall(
            r"^\s*(" + spec["prefix"] + r"[A-Z_]+)\s*=\s*\d+;", match.group(1), re.M
        )
        if not values:
            print(f"{spec['enum']} in {proto} has no values", file=sys.stderr)
            return 1

        fixture = collections.OrderedDict()
        fixture["_comment"] = spec["comment"]
        fixture["constants"] = collections.OrderedDict(
            (name[len(spec["prefix"]):], name) for name in values
        )

        out = ROOT / "testdata" / spec["fixture"]
        out.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {len(values)} values to {out.relative_to(ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
