#!/usr/bin/env python3
"""Regenerates testdata/event-types.json from the published proto.

The clients are hand-written on purpose — there is no protobuf runtime and no
generated code to keep in step, which is the whole reason the wire contract is
written down in docs/WIRE.md. So this does not generate the constants. It
generates the list the three test suites check them against, which keeps the
proto the source of truth without putting a code generator in the build.

Run it after scripts/sync-proto.sh, and commit whatever it produces.
"""

import collections
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROTO = ROOT / "proto" / "panmail" / "v1" / "event.proto"
FIXTURE = ROOT / "testdata" / "event-types.json"
PREFIX = "EMAIL_EVENT_TYPE_"

COMMENT = [
    "Every value of EmailEventType in proto/panmail/v1/event.proto, and the",
    "only place the three clients' Status constants are written down together.",
    "Each suite reads this and asserts its own client exposes exactly these, so",
    "a value added to the proto that the clients do not follow fails all three.",
    "",
    "Generated by scripts/sync-status.py. Do not hand-edit: run that after the",
    "proto changes, the same way the protos themselves are synced.",
    "",
    "UNSPECIFIED is here because the proto has it. It is the zero value",
    "protobuf requires, not a state a message is ever in.",
]


def main() -> int:
    source = PROTO.read_text(encoding="utf-8")
    match = re.search(r"enum EmailEventType \{(.*?)\n\}", source, re.S)
    if match is None:
        print(f"no EmailEventType enum in {PROTO}", file=sys.stderr)
        return 1

    values = re.findall(r"^\s*(" + PREFIX + r"[A-Z_]+)\s*=\s*\d+;", match.group(1), re.M)
    if not values:
        print(f"EmailEventType in {PROTO} has no values", file=sys.stderr)
        return 1

    fixture = collections.OrderedDict()
    fixture["_comment"] = COMMENT
    fixture["constants"] = collections.OrderedDict(
        (name[len(PREFIX):], name) for name in values
    )

    FIXTURE.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(values)} event types to {FIXTURE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
